### ISSUE TITLE
visualizeMap.py cannot work with negative coordinates

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [nilsgawlik/gdmc_http_client_python#71]
**Feature branch: `None`**
When using a buildarea with negative coordinates, a `ValueError: negative dimensions are not allowed` is thrown.

### Error:
```py
Traceback (most recent call last):
  File "visualizeMap.py", line 18, in <module>
    slice = WorldSlice(x1, z1, x2, z2)
  File "/home/rafael_novotny/memory_module/Code/GDMC/gdmc_http_client_python/gdpc/worldLoader.py", line 65, in __init__
    self.heightmaps[hmName] = np.zeros(
```

### Suggested implementation:

```py
def what_I_imagine():
    ...
```

Pro:
- [fill me]

Con:
- [fill me]

**Comment by caranha** [comment]
I think #67 solves this.

**Comment by avdstaaij** [comment]
Moved to https://github.com/avdstaaij/gdpc/issues/41
